Project Flight Manager/Controllers/AdministrationController.cs
namespace Project_Flight_Manager.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Project_Flight_Manager.Services.Contracts;
    using Project_Flight_Manager.ViewModels.Administration;
    using System.Security.Claims;
    using System.Threading.Tasks;

    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        private readonly IAdministrationService administrationService;

        public AdministrationController(IAdministrationService administrationService)
        {
            this.administrationService = administrationService;
        }

        public IActionResult AdminPanel()
        {
            return this.View();
        }

        public async Task<IActionResult> Users(int? pageNumber, string filter)
        {
            int pageSize = 10;

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var model = await this.administrationService.GetUsers(10, filter, userId);
            var pagedModel = await PaginatedList<UserViewModel>.CreateAsync(model, pageNumber ?? 1, pageSize);
            return this.View(pagedModel);
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            await this.administrationService.DeleteUser(id);
            return this.Redirect("/Administration/Users");
        }
    }
}

Project Flight Manager/Controllers/FlightDataModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project_Flight_Manager.Data;
using Project_Flight_Manager.Models;
using Project_Flight_Manager.Services.Contracts;
using Project_Flight_Manager.ViewModels.Administration;
using Project_Flight_Manager.ViewModels.Flights;

namespace Project_Flight_Manager.Controllers
{
    public class FlightDataModelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IFlightsService flightsService;

        public FlightDataModelsController(ApplicationDbContext context, IFlightsService flightsService)
        {
            _context = context;
            this.flightsService = flightsService;
        }

        // GET: FlightDataModels
        public async Task<IActionResult> Index(int? pageNumber, string filter)
        {
            int pageSize = 10;

            var model = await this.flightsService.GetFlights(10, filter);
            var pagedModel = await PaginatedList<FlightViewModel>.CreateAsync(model, pageNumber ?? 1, pageSize);
            return this.View(pagedModel);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await this.flightsService.GetFlight(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: FlightDataModels/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(FlightDataModel flightDataModel)
        {
            if (flightDataModel.DepatureTime > flightDataModel.ArrivalTime)
            {
                ModelState.AddModelError("ArrivalTime", "Arrival time cannot be earlier than departure time!");
                ModelState.AddModelError("DepatureTime", "Departure Time cannot be later than arrival time!");
            }
            if (ModelState.IsValid)
            {
                _context.Add(flightDataModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flightDataModel);
        }

        // GET: FlightDataModels/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightDataModel = await _context.Flights.FindAsync(id);
            if (flightDataModel == null)
            {
                return NotFound();
            }
            return View(flightDataModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, FlightDataModel flightDataModel)
        {
            if (id != flightDataModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flightDataModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightDataModelExists(flightDataModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flightDataModel);
        }

        // GET: FlightDataModels/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightDataModel = await _context.Flights
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flightDataModel == null)
            {
                return NotFound();
            }

            return View(flightDataModel);
        }

        // POST: FlightDataModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var flightDataModel = await _context.Flights.FindAsync(id);
            _context.Flights.Remove(flightDataModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // 
        private bool FlightDataModelExists(string id)
        {
            return _context.Flights.Any(e => e.Id == id);
        }
    }
}

Project Flight Manager/Controllers/ReservationDataModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project_Flight_Manager.Data;
using Project_Flight_Manager.Models;
using Project_Flight_Manager.Services.Contracts;
using Project_Flight_Manager.ViewModels.Reservations;

namespace Project_Flight_Manager.Controllers
{
    public class ReservationDataModelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IReservationsService reservationsService;

        public ReservationDataModelsController(ApplicationDbContext context, IReservationsService reservationsService)
        {
            _context = context;
            this.reservationsService = reservationsService;
        }

        // GET: ReservationDataModels
        public async Task<IActionResult> Index()
        {
            var model = await _context.Reservations.ToListAsync();
            return View(model);
        }

        // GET: ReservationDataModels/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservationDataModel = await this.reservationsService.ReservationDetails(id);
            if (reservationDataModel == null)
            {
                return NotFound();
            }

            return this.View(reservationDataModel);
        }

        // GET: ReservationDataModels/Create
        public IActionResult Create(string flightId)
        {
            var model = new ReservationInputModel()
            {
                FlightId = flightId,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReservationInputModel model)
        {
            if (ModelState.IsValid)
            {
                await this.reservationsService.CreateReservation(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: ReservationDataModels/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservationDataModel = await _context.Reservations.FindAsync(id);
            if (reservationDataModel == null)
            {
                return NotFound();
            }
            var model = new ReservationEditInputModel()
            {
                FirstName = reservationDataModel.FirstName,
                LastName = reservationDataModel.LastName,
                EGN = reservationDataModel.EGN,
                MiddleName = reservationDataModel.MiddleName,
                Nationality = reservationDataModel.Nationality,
                TelNumber = reservationDataModel.TelNumber,
                TicketType = reservationDataModel.TicketType,
                ReservationId = id,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ReservationEditInputModel reservationDataModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this.reservationsService.EditReservation(reservationDataModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationDataModelExists(reservationDataModel.FirstName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reservationDataModel);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservationDataModel = await _context.Reservations
                .FirstOrDefaultAsync(m => m.FirstName == id);
            if (reservationDataModel == null)
            {
                return NotFound();
            }

            return View(reservationDataModel);
        }

        [HttpPost("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var reservationDataModel = await _context.Reservations.FindAsync(id);
            _context.Reservations.Remove(reservationDataModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationDataModelExists(string id)
        {
            return _context.Reservations.Any(e => e.FirstName == id);
        }
    }
}

Project Flight Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Flight_Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<style>
	body {
	background-image: url("/image/sky.jpg");
	background-size: cover;
	}
	.display-4{
	font-family:"Palatino Linotype", "Book Antiqua", Palatino, serif;
	color:white;
	margin-top:300px;
	text-shadow: 3px 3px rgba(163, 167, 204, 0.2);
	-webkit-text-stroke: 1px rgba(163, 167, 204, 1);
	-webkit-text-fill-color: white;

	}
	.display-3{
	font-family:"Palatino Linotype", "Book Antiqua", Palatino, serif;
	color:white;
	margin-top:50px;
	text-shadow: 3px 3px rgba(163, 167, 204, 0.2);
	-webkit-text-stroke: 1px rgba(163, 167, 204, 1);
	-webkit-text-fill-color: white;

	}
	element-style{
	background-color: black;
	}
	.navbar{
	opacity:0.6;
	}
	.navbar-light .navbar-brand {
	color: white;
	text-shadow: 1px 1px #000000;
	}

	.navbar-light .navbar-nav .nav-link {
	background-color: black;
	color: #fff !important;
	text-shadow: 1px 1px #000000;
	}
	.bg-white{
	color:black;
	}
</style>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #000000;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Flight Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="AdminPanel">Admin Panel</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FlightDataModels" asp-action="Index">Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ReservationDataModels" asp-action="Index">Reservations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Project_Flight_Manager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>